#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

source "$HOME/.nvm/nvm.sh"

# 檢查 nvm 是否安装
if command -v nvm &> /dev/null; then
  node_version="$(nvm version)"
  nvmrc_path="$(nvm_find_nvmrc)"
  if [ -n "$nvmrc_path" ]; then
      nvmrc_node_version=$(nvm version "$(cat "${nvmrc_path}")")
      if [ "$nvmrc_node_version" = "N/A" ]; then
        nvm install
      elif [ "$nvmrc_node_version" != "$node_version" ]; then
        nvm use
      fi
      echo "成功安裝 node 版本: $(nvm version)"
    elif [ "$node_version" != "$(nvm version default)" ]; then
      echo ".nvmrc not found"
    fi
else
  echo "nvm is not installed."
fi

