name: Build Galao
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14.x
          cache: "npm"
      - name: Echo secret
        run: echo ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Install dependencies
        run: npm ci
      - name: Build
        uses: borales/actions-yarn@v4
        with:
          cmd: build
