name: Husky Hook

on:
  push:
    branches:
      - main # 你的默认分支名称

jobs:
  husky-hook:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14 # 替换为你希望使用的 Node.js 版本

      - name: Install Node.js dependencies
        run: npm ci

      - name: Process directories
        run: |
          function process_directory() {
            echo "Entering $1"

            if [ -f "$1/package-lock.json" ]; then
              echo "Found package-lock.json in $1"
              (cd "$1" && npm ci)
            fi

            if [ "$(cat "$1/package.json" | grep -c "webpack")" -gt 0 ]; then
              echo "Found webpack script in $1"
              (cd "$1" && yarn webpack)
            fi

            for sub_dir in "$1"/*; do
              if [ -d "$sub_dir" ] && [ "$(basename "$sub_dir")" != "node_modules" ]; then
                process_directory "$sub_dir"
              fi
            done
          }

          top_dir="./src"
          process_directory "$top_dir"

      - name: Run webpack
        run: npm run build

      - name: Commit changes
        run: |
          git config user.name "ycjoyce"
          git config user.email "yeechiajoyce@gmail.com"
          git add -A
          git commit -m "Auto commit by GitHub Actions"
