name: Build Galao
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14.x
          cache: "npm"
      - name: Set SSH key
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Find files with package.json
        id: find-package-json
        run: |
          {
            echo 'PACKAGE_PATHS<<EOF'
            find . -type f -name package.json -not -path "*/node_modules/*" -exec dirname {} \;
            echo EOF
          } >> "$GITHUB_OUTPUT"
      - name: Install dependencies
        # 所有有 package.json 的檔案都應該要執行 npm install
        run: |
          IFS=$'\n' read -ra PACKAGE_PATHS <<< "${{ steps.find-package-json.outputs.PACKAGE_PATHS }}"
          for item in "${items[@]}"; do
            echo "Installing dependencies in $item"
            cd $(dirname $item)
            npm install
            cd - > /dev/null
          done
      - name: Build
        run: npm run build
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: ${{ github.workspace }}/build
  download:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v3
        with:
          name: build
          path: ~/download/build
