name: Build Galao
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14.x
          cache: "npm"
      - name: Set SSH key
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Find files with package.json
        id: find-package-json
        run: |
          $files = $(find . -name "package-lock.json" -print)
          echo "files=$files" >> "$GITHUB_OUTPUT"
      - name: Install dependencies
        # TODO: 所有有 package.json 的檔案都應該要執行 npm ci
        run: |
          for file in ${{ steps.find-package-json.outputs.files }}; do
            echo "Installing dependencies in $file"
            cd $(dirname $file)
            npm ci
            cd - > /dev/null
          done
      - name: Build
        uses: borales/actions-yarn@v4
        with:
          cmd: build
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: ${{ github.workspace }}/build
  download:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v3
        with:
          name: build
          path: ~/download/build
