name: Build Galao
on:
  push:
    branches:
      - "!master"
      - "!develop"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14.x
          cache: "npm"
      - name: echo ssh key
        run: echo ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Set SSH key
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Install dependencies
        # TODO: 所有有 package.json 的檔案都應該要執行 npm ci
        run: npm ci
      - name: Build
        uses: borales/actions-yarn@v4
        with:
          cmd: build
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: ${{ github.workspace }}/build
      - name: Get Workflow YAML Path
        run: echo '$GITHUB_WORKSPACE/.github/workflows/$GITHUB_WORKFLOW.yml'
